### ISSUE TITLE
Problem running Lp3 function

### ISSUE THREAD

**Issue by jnelson7** [dblodgett-usgs/NWCEd#16]
The Lp3 function runs locally when copying and pasting in the R console.  However, when knitting the Lab_5.rmd file to HTML, the Lp3 function is not recognized.  Do you know why this is and how I might be able to fix it?

**Comment by dblodgett-usgs** [comment]
I'll have to take a close look at what it's doing and get back to you. It may be that you have not run roxygen to get the function into the man pages and the NAMESPACE. You can see how to turn roxygen on here: https://support.rstudio.com/hc/en-us/articles/200532317-Writing-Package-Documentation

Also make sure you have roxygen2 installed!

**Comment by dblodgett-usgs** [comment]
Working through this. 
- you need to add newly imported packages to the DESCRIPTION file by hand.
- I left some questions and pointers for you in the roxygen block at the top of Lp3. Please also use the @importFrom rather than import. like: `@importfrom packageName functionName`
- You were loading some data in a way that won't work unless the code is run in your present working directory. You'll see I moved the data into a sysdata.rda file. You can read up on package data here: http://r-pkgs.had.co.nz/data.html

Will pull request and merge these changes. Lab 5 knits now. This is cool. We should get this function tested and do some refactoring, but I'm impressed!

**Comment by jnelson7** [comment]
Thank you for your help!  I'll go ahead and make those changes. 

Jake Nelson

**Comment by dblodgett-usgs** [comment]
No problem. This function is great... I was actually looking for exactly this functionality earlier this week! It'll be great to have.
